version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: main
      # You should definitely change the password in production
      POSTGRES_PASSWORD: main
      POSTGRES_USER: main
    volumes:
      - postgres:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  postgres:
###< doctrine/doctrine-bundle ###
